const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Zokou-MD-WHATSAPP-BOT;;;=>eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS0g1TTZxbzFkV0VRdDBVWDBRakZIajcxVE5EZmh3NmpoSS9mZTlZd2JWYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicXI0WnBFMWIrbU1YTkhXNzJ1U05PVHM4Ry9wQVZ6TE9tMGNZSDAzYXhrbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjTUNMdUdLa1RaK0Q3TmN1U2Y3cE8zZ3FoVkZDbjVDZ1ZubzM4OHU0ajNzPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJmTjhScVpvLy9TdkJpRloxVVJQVHJiUFhzcWpMa2NDMjF2UzY5N3FBRmhJPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im1CcHJyT2NabVNZbXZnNXFROS9ITGkvdW9rNVhzUlRmemRBWFhkdEVPMGs9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Iis4RHYxT002bFhjcE9rSEtYQlhHaFkwOHRsNy9DNUg4SmpKWGJSSi9sQkU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0tKNUZuKzZLZkIxUDBXdmFFeUw0ZDBQU3VPM3Exc01WVGtaVnoxbUsyWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWjRRTFBQR0hRVU8yY2dwc2hFMGtwTDVNbzY5VER1d0tyeDJzRjNnSGZoOD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlA2czRkeE1uanJSREM1WWtjOERrSmZNTzNNeUJFRjB1YnhVSW90Q3l3TEg4cEw5c1V5eDFEL3gwSlZQNU43QUt0UmdBZ0Qva0R2TU9ZODUvV2RYdEFBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjgsImFkdlNlY3JldEtleSI6InhKanJjc2FsN3lyclR3aUJvRGdDL1JKeW5tQldTWGlqUE50OUxZNkhsekU9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IjdXeGxzY3JqUVp5MW1vajBiNUNtQXciLCJwaG9uZUlkIjoiYzgxNzc5MDMtMDY3Ni00MTQ0LThmYmMtZTU4YjQ5ZDhlOTQxIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlBoYnpiS3h5ZEZlUVFuWVNvRDdtdmZ2eGJuQT0ifSwicmVnaXN0ZXJlZCI6ZmFsc2UsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV0NId1l2eVpBd1Y5alArbUR1TE5oc3lmL2dBPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSlBHZ3M4Q0VPL1B4cjBHR0FRZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiS2l6aFFzdmYyeXJicngvLytRNm52ZkhYQ0hsQnVzOWlqRTNoaEtObkhpcz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiWGpCTUIvUUFYZDdra1hDK0VwVXk2ckg4NU5ic3hKR1JEYWptZjdtY2x0UVJsbUg2bkVobUJrbDRCQStBWkNiMzFIUVpubGRqMlFrY2E3ejdwNWN6QXc9PSIsImRldmljZVNpZ25hdHVyZSI6IjBSTEFGeUVRZXVROWRNcldlTDlUTkkrN0hQTDJ6N1NIMzIxRHhNdmdmR2F4ZkpJTlJWcm5lbU02VEpnREVuM0Q2ZnpDSjVKeGNtVm1waE9weC9iK0F3PT0ifSwibWUiOnsiaWQiOiIyMjE3ODIyNzM5MzA6MTJAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiIxMTc5NTI4MDQyOTA3NDU6MTJAbGlkIn0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIyMTc4MjI3MzkzMDoxMkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJTb3M0VUxMMzlzcTI2OGYvL2tPcDczeDF3aDVRYnJQWW94TjRZU2paeDRyIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQWdJQWc9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3Mzk2OTYxMTUsImxhc3RQcm9wSGFzaCI6IjNnUFVKayJ9",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Douzzy",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
